apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-health
  namespace: {{ .Values.namespace }}
  labels:
    app: node-health
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: node-health
      labels:
        app: node-health
      annotations:
        releasetime: {{ $.Release.Time }}
    spec:
      serviceAccountName: node-health
      containers:
      - image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: node-health
        args:
        - daemon
        - --config.dirs=/var/run/node-health/configmap/
        - --config.files=config
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 55m
            memory: 150Mi
          limits:
            cpu: 55m
            memory: 150Mi
        volumeMounts:
        - name: node-health-configmap
          mountPath: /var/run/node-health/configmap/
      volumes:
      - name: node-health-configmap
        configMap:
          name: node-health-configmap
          items:
          - key: config.yaml
            path: config.yaml
