apiVersion: v1
kind: Service
metadata:
  name: node-health
  namespace: {{ .Values.namespace }}
  labels:
    app: node-health
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: node-health
  type: NodePort
