apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-node-health-configmap
  namespace: {{ .Values.namespace }}
  labels:
    app: kubernetes-node-health
    giantswarm.io/service-type: "managed"
data:
  config.yaml: |
    server:
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
