apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubernetes-node-health
  namespace: {{ .Values.namespace }}
  labels:
    app: kubernetes-node-health
    giantswarm.io/service-type: "managed"
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: kubernetes-node-health
  template:
    metadata:
      name: kubernetes-node-health
      labels:
        app: kubernetes-node-health
        giantswarm.io/service-type: "managed"
      annotations:
        releasetime: {{ $.Release.Time }}
    spec:
      serviceAccountName: kubernetes-node-health
      containers:
      - image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: kubernetes-node-health
        args:
        - daemon
        - --config.dirs=/var/run/kubernetes-node-health/configmap/
        - --config.files=config
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 55m
            memory: 150Mi
          limits:
            cpu: 55m
            memory: 150Mi
        volumeMounts:
        - name: kubernetes-node-health-configmap
          mountPath: /var/run/kubernetes-node-health/configmap/
      volumes:
      - name: kubernetes-node-health-configmap
        configMap:
          name: kubernetes-node-health-configmap
          items:
          - key: config.yaml
            path: config.yaml
