apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubernetes-node-health
  namespace: {{ .Values.namespace }}
  labels:
    app: kubernetes-node-health
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  resourceNames:
  - kubernetes-node-health
  verbs:
  - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-node-health
  namespace: {{ .Values.namespace }}
  labels:
    app: kubernetes-node-health
subjects:
- kind: ServiceAccount
  name: kubernetes-node-health
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: kubernetes-node-health
  labels:
    app: kubernetes-node-health
  apiGroup: rbac.authorization.k8s.io
