apiVersion: v1
kind: Service
metadata:
  name: kubernetes-node-health
  namespace: {{ .Values.namespace }}
  labels:
    app: kubernetes-node-health
    giantswarm.io/service-type: "managed"
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: kubernetes-node-health
  type: NodePort
